# Path to the directory with your mind maps
mindMapsDir: "~/Documents/Mind Maps"

# Glob pattern for finding files to include in search
filesToSearch: "**/*.smmx"

# Locale for date formatting
locale: en-GB
